// This file was auto-generated by ML.NET Model Builder. 

using System;
using Capita001ML.Model;

namespace Capita001ML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Feature = @"Notification",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Product with predicted Product from sample data...\n\n");
            Console.WriteLine($"Feature: {sampleData.Feature}");
            Console.WriteLine($"\n\nPredicted Product value {predictionResult.Prediction} \nPredicted Product scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
