// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace Capita001ML.Model
{
    public class ModelInput
    {
        [ColumnName("Feature"), LoadColumn(0)]
        public string Feature { get; set; }


        [ColumnName("Product"), LoadColumn(1)]
        public string Product { get; set; }


        [ColumnName("Score"), LoadColumn(2)]
        public float Score { get; set; }


    }
}
